In [40]:
import pandas as pd

obj=pd.Series([2,3,4,-5,20,10,9], index=["hello", "what", "really", "damn", "jesus", "really2?", "wow"])


obj*2

obj*3

hello        6
what         9
really      12
damn       -15
jesus       60
really2?    30
wow         27
dtype: int64

In [41]:
obj*-1

hello       -2
what        -3
really      -4
damn         5
jesus      -20
really2?   -10
wow         -9
dtype: int64

In [42]:
obj*2

hello        4
what         6
really       8
damn       -10
jesus       40
really2?    20
wow         18
dtype: int64

In [53]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

myDataframe=pd.DataFrame(data)

myDataframe

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [62]:
data2=pd.read_csv("Train.csv")
data2.tail()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0

In [67]:
selected_columns=pd.DataFrame(data2, columns=["ID", "Cost_of_the_Product", "haha"])
selected_columns

          ID  Cost_of_the_Product  haha
0          1                  177   NaN
1          2                  216   NaN
2          3                  183   NaN
3          4                  176   NaN
4          5                  184   NaN
...      ...                  ...   ...
10994  10995                  252   NaN
10995  10996                  232   NaN
10996  10997                  242   NaN
10997  10998                  223   NaN
10998  10999                  155   NaN

[10999 rows x 3 columns]

In [73]:
data2=pd.DataFrame(data2)
data2["Cost_of_the_Product"]

0        177
1        216
2        183
3        176
4        184
        ...
10994    252
10995    232
10996    242
10997    223
10998    155
Name: Cost_of_the_Product, Length: 10999, dtype: int64

In [80]:
data2.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [81]:
data2.loc[0]

ID                          1
Warehouse_block             D
Mode_of_Shipment       Flight
Customer_care_calls         4
Customer_rating             2
Cost_of_the_Product       177
Prior_purchases             3
Product_importance        low
Gender                      F
Discount_offered           44
Weight_in_gms            1233
Reached.on.Time_Y.N         1
Name: 0, dtype: object